# Netlify configuration
[build]
  publish = "."

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"

# Trigger auto-reply on form submission
[[events]]
  package = "@netlify/functions"
  event = "submission-created"
  # Map to our function
  # In background:handled by function file name
